### ISSUE TITLE
Switch to toggle Syncthing on and off is grayed out and unresponsive.

### ISSUE THREAD

**Issue by terrycloth** [jaystrictor/gnome-shell-extension-syncthing#1]
The switch to toggle Syncthing on and off is unresponsive. The Syncthing switch is grayed out. When I click on the switch, nothing happens. 

![Screenshot of the Syncthing Icon GNOME Shell extension in action.](https://cloud.githubusercontent.com/assets/3881885/10382325/b1482dd4-6dd7-11e5-8838-cf271c32f2cb.png)

I'm running Syncthing v0.11.26 on Fedora 22 (64-bit) with GNOME 3.16.3.

GUI Listen Address: 127.0.0.1:8384
Sync Protocol Listen Address: 0.0.0.0:22000

Let me know if you need any other info.

**Comment by jaystrictor** [comment]
The switch is set to sensitive/insensitive according to the ouput of
```sh
/usr/bin/systemctl --user is-active syncthing.service
```

What is the output of the above line on your system?

Are the unit files even installed on your system? You can check with
```sh
systemctl list-unit-files | grep -i syncthing
systemctl --user list-unit-files | grep -i syncthing
```

**Comment by terrycloth** [comment]
Oh, no, I don't have any of the Systemd unit files. The "install" script doesn't check on systemd, and when I cloned the repository a few days ago, the README didn't say anything about systemd.

Where do I get the unit files? Was this recently added to Syncthing or something?

**Comment by jaystrictor** [comment]
The comment about systemd has been in the README since the initial commit.

Could it be that Syncthing is already started when you try to start it with 
```sh
systemctl --user start syncthing.service
```
?

How do you start Syncthing usually?

**Comment by jaystrictor** [comment]
Another idea:
You have installed the binary somewhere below `~/apps/Syncthing/` but
in the systemd unit file it states
```
ExecStart=/usr/bin/syncthing -no-browser -logflags=0
```

Maybe systemd cannot find the Syncthing binary there.
Check where the syncthing binary resides and change the above line accordingly.

**Comment by terrycloth** [comment]
> The comment about systemd has been in the README since the initial commit.

You're right. My mistake. I guess, since I read about the premise of the shell extension in your announcement post on the forum, when I came to this repo's README, I skipped to the installation section. Still, it might be good to mention that this extension relies on the systemd unit file, and that that should be setup first.

You were also right that systemctl wasn't finding the Syncthing executable. The default Syncthing offering for Linux is just a self-executing binary instead of a deb or rpm, so I'd just kept it in ~/apps with other such executables and scripts on my system.

I edited the line containing `ExecStart=` in the file `~/.config/systemd/user/syncthing.service`
and I ran `systemctl --user daemon-reload`

Now the systemd service and the GNOME Shell extension work as they should. Thanks!

**Comment by jaystrictor** [comment]
> Still, it might be good to mention that this extension relies on the systemd unit file, and that that should be setup first.

Thanks for the feedback. It's very much appreciated.

I added a comment to the README file about systemd. Should be enough, but if you think it still needs further clarification, then just open a pull request.
