### ISSUE TITLE
Integrate into system menu

### ISSUE THREAD

**Issue by kkharinarayanan** [jaystrictor/gnome-shell-extension-syncthing#10]
Hii sorry for the delay in raising the issue in git 

I believe that syncing should come as a part of system. Hence the icon should go into he system status menu, ie with the wifi icon etc

**Comment by jaystrictor** [comment]
Hmm, I am not so sure about this. Syncthing is just one application and is not really a part of the operating system.
The area where the network and volume and on/off symbols reside on the other hand is more universal. It represents the current state of the entire session.

Therefore I think the syncthing icon should stay where it is.
