### ISSUE TITLE
Alignment in the popup

### ISSUE THREAD

**Issue by kkharinarayanan** [jaystrictor/gnome-shell-extension-syncthing#13]
Hii
The on/off button and configuration icon are not aligned in the popup. I fixed this by adding spaces in line 253 of extension.js. But since this is not a good solution, please see if you can fix it by having  a grid or something.
![Fixed](https://cloud.githubusercontent.com/assets/915776/14205731/273ceed4-f82b-11e5-946f-5436d23c9d13.png)
Fixed version
![original](https://cloud.githubusercontent.com/assets/915776/14205752/544f4674-f82b-11e5-9c25-511bfc7f9ebd.png)
Original version

**Comment by jaystrictor** [comment]
Actually, this icon should be aligned at the end of the line, as specified in the [gnome-shell source](https://git.gnome.org/browse/gnome-shell/tree/js/ui/popupMenu.js?h=3.20.0#n398).

This seems to be a bug in gnome-shell.
