### ISSUE TITLE
Show folder label instead of folder ID in menu

### ISSUE THREAD

**Issue by gdetrez** [jaystrictor/gnome-shell-extension-syncthing#18]
Syncthing [0.13](https://github.com/syncthing/syncthing/releases/tag/v0.13.0) introduced folders labels:

> Folder labels are now distinct from the folder ID. The intention is for the label to be human readable and for the ID to be machine readable and unique.

**Comment by jaystrictor** [comment]
Thank you! Should be fixed now. Otherwise, please reopen.

**Comment by gdetrez** [comment]
Thanks, that was quick!
