### ISSUE TITLE
Display the folder label instead of its ID

### ISSUE THREAD

**Issue by cdevienne** [jaystrictor/gnome-shell-extension-syncthing#19]
My folder IDs are random strings.
I would prefer the folder labels to appear in the menu, and I think syncthing UIs are expected to show these labels, not the IDs.

It would be great to have this!

**Comment by cdevienne** [comment]
my bad, it seems it was implemented some 19 days ago... Is the extension up-to-date on extensions.gnome.org ?

**Comment by jaystrictor** [comment]
Oh yes, this should already be implemented, but I forgot to send it to extensions.gnome.org for review.

I did this now. Usually it takes several days until they approve it.

**Comment by cdevienne** [comment]
Thank you @jaystrictor !

**Comment by jaystrictor** [comment]
This should now be on extensions.gnome.org.

**Comment by cdevienne** [comment]
Thanks !
