### ISSUE TITLE
Error: Type name WorkspaceNameModel is already registered

### ISSUE THREAD

**Issue by miclill** [jaystrictor/gnome-shell-extension-syncthing#2]
Can't really do more than paste the exception but I do want to thank you for doing this project.
I would definitely use it. Thank you.
Gnome-Shell-Version: 3.14 on debian stable

Error: Type name WorkspaceNameModel is already registered

Stack trace:
  GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:125
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
  @/home/sam/.local/share/gnome-shell/extensions/syncthing@michael.lill.posteo.de/prefs.js:108
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:80
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:260
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:398
  @<main>:1

**Comment by jaystrictor** [comment]
You're welcome :)

Why do you have
```
@/home/sam/.local/share/gnome-shell/extensions/syncthing@michael.lill.posteo.de/prefs.js:108
```
?

The extension should rather be in `local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de>`. Did you rename the directory?

**Comment by miclill** [comment]
Turns out those were leftovers from when I was working on an extension myself. (tldr: i'm stupid :-))
