### ISSUE TITLE
syncthing panel icon with warning?

### ISSUE THREAD

**Issue by johnnydvc** [jaystrictor/gnome-shell-extension-syncthing#24]
Is this supposed to be like that.
thank you
![image](https://cloud.githubusercontent.com/assets/4787052/20946006/5ed60162-bc09-11e6-8190-34963c269ce4.png)

**Comment by jaystrictor** [comment]
Only when the extension has a problem.
What does `journalctl /usr/bin/gnome-shell -e` say?

Maybe issue #21 is related.

**Comment by johnnydvc** [comment]
jeah you're right. its the same bug as [#21](https://github.com/jaystrictor/gnome-shell-extension-syncthing/issues/21).
so the solution would be a properly signed certificate.
thank you
