### ISSUE TITLE
Open default web browser using the "web interface"

### ISSUE THREAD

**Issue by KopfKrieg** [jaystrictor/gnome-shell-extension-syncthing#27]
It would be nice to have an option to open a new tab in the default web browser instead of opening a completely different window if the "web interface" button is pressed. Is this possible?

**Comment by jaystrictor** [comment]
This was already implemented by @Palatis in PR #23 , I think.

Maybe I have forgotten (again) to upload the changes to extensions.gnome.org. Is this your problem?

**Comment by jaystrictor** [comment]
The current github version is now uploaded to extensions.gnome.org.
You should be able to upgrade to the newest version.
After that start
```
gnome-shell-extension-prefs syncthingicon@jay.strict@posteo.de
```
and click on `Always use external browser`.
This should do it.

**Comment by Palatis** [comment]
:-D

**Comment by KopfKrieg** [comment]
Jep, upgrade is now available and I updated. Thanks!
