### ISSUE TITLE
not displaying that syncthing is running

### ISSUE THREAD

**Issue by joaoherberto** [jaystrictor/gnome-shell-extension-syncthing#28]
Manjaro Gnome-
Hello, I have syncthing running as a user service at start up, I enabled it using sudo systemctl enable syncthing@<myusername>.service and it will run for my user account even if I am not logged in but computer is running.

I am trying your extension but it does not detect that the server is already running, if I turn it "On" it will stay on for a while then switch to "Off", but the service is still running. While it is on the "On" position, it will open the web interface.

I added the API to the settings but to no avail.

Am I missing something?

**Comment by jaystrictor** [comment]
If you enter `sudo systemctl ...` then you have syncthing started from a systemd **system service**.

This extension uses the **user service** management facilities of systemd. The [Syncthing documentation](https://docs.syncthing.net/users/autostart.html#how-to-set-up-a-user-service) has information about how to set this up. Please make sure that you have the user units installed correctly, otherwise the on/off switch will not work.

**Comment by joaoherberto** [comment]
OK, you answered my question, the extension does not work with a system service but with user service, there are two ways to run syncthing, you can have multiple syncthing system services that run at boot and will function whether the user is actually logged in or not, example would be my current setup, `sudo systemctl enable syncthing@joao.service`, this will start syncthing service for my user account as a system service and will sync perfectly even though I may not be logged into my account..

The other option is to have syncthing start a service when the user logs in to their account, this would be a user service and this is what the extension is working off of correct?

**Comment by jaystrictor** [comment]
Yes, mostly correct.

However you are missing one important point: systemd user services can "linger". You can enable lingering by typing `loginctl enable-linger username`.
That way the user services run even when the user is not logged in.
