### ISSUE TITLE
Detect syncthing running from syncthing-gtk

### ISSUE THREAD

**Issue by omega** [jaystrictor/gnome-shell-extension-syncthing#29]
This is sort of a wishlist, but it would be awesome if it could detect the daemon that syncthing-gtk runs and show the status as On (but perhaps disabled button?) somehow.

**Comment by jaystrictor** [comment]
I think it is generally difficult to handle all the different possibilities for starting a syncthing daemon. Therefore I concentrated on only handling systemd user service.

E.g.:
- How should the button behave if both syncthing-gtk has a daemon running and another systemd user service is running?
- What if a user service and a system service is running?
- Combine the both bullet points above. How to behave?
- etc.

**Comment by omega** [comment]
Hey, yeah, I agreed, and once I found out it supported systemd, I changed to that and it works, great :) syncthing-gtk also speaks with that so it feels like an allround better solution as well
