### ISSUE TITLE
Extension doesn't work on Gnome Shell 3.26

### ISSUE THREAD

**Issue by KopfKrieg** [jaystrictor/gnome-shell-extension-syncthing#30]
I've upgrade gnome-shell to v3.26 (on Arch Linux), and the extensions doesn't work anymore. Adding "3.26" to metadata.json doesn't work, the error message is always the same:

```Extension "syncthingicon@jay.strict@posteo.de" had error: Error: Expected type GType for Argument 'type' but got type 'string'```

**Comment by jaystrictor** [comment]
Thank you for your bug report.
For me this seems like a bug in gnome-shell. They don't properly support the string type for the icon argument anymore in the constructor of PopupImageMenuItem. Do you want to file a bug report for gnome-shell or should I do it?

Anyways, for the time being I wrote a simple workaround for this extension. It should work now.

**Comment by KopfKrieg** [comment]
Awesome, thanks!

Would be nice if you could file the bug report for gnome-shell :)

**Comment by jaystrictor** [comment]
Bug report for gnome-shell: https://bugzilla.gnome.org/show_bug.cgi?id=789018

**Comment by KopfKrieg** [comment]
Thank you
