### ISSUE TITLE
Compatibility with 3.30

### ISSUE THREAD

**Issue by KopfKrieg** [jaystrictor/gnome-shell-extension-syncthing#36]
Currently the extension is not officially compatible with Gnome Shell v3.30. Could you make it compatible? It's probably just a version adjustment necessary.

**Comment by jaystrictor** [comment]
I cannot test this on 3.30. Could someone just confirm that the extension works on 3.30, then I am happy to bump the version.

**Comment by KopfKrieg** [comment]
I'm sorry, but after playing around with it, I think a version adjustment alone won't be enough. Unfortunately I also don't know how to debug that :/

**Comment by fipm** [comment]
I can confirm the error when trying to enable the extension in 3.30.

**Comment by jaystrictor** [comment]
Ahh I missed your edit @KopfKrieg.
Sorry. Trying to fix that now.

**Comment by jaystrictor** [comment]
@njam did some work on this.

Could you test the current commit and report back how it works for you, @KopfKrieg ?

**Comment by sanjayankur31** [comment]
@jaystrictor : I installed commit fe6f651 manually, and seems to work just fine. The icon is back in the top bar, and the buttons etc. are all functional too. Thanks :)

```
$ rpm -q gnome-shell
gnome-shell-3.30.1-1.fc29.x86_64
```

**Comment by KopfKrieg** [comment]
@jaystrictor I can confirm the latest commit ([fe6f651](https://github.com/jaystrictor/gnome-shell-extension-syncthing/commit/fe6f651a65c78bb3243764b598689710eed1fc2a)) is working with gnome-shell 3.30.1.

**Comment by jaystrictor** [comment]
Thank you both for testing. Uploaded the new version to extensions.gnome.org.
Should be online after review.

**Comment by da-n** [comment]
I might be missing something obvious, sorry if this is the case, but the most recent version on extensions.gnome.org seems to be against 3.26? Am I being dumb? Thanks.

**Comment by jaystrictor** [comment]
As I said, I uploaded the new version. That doesn't mean that you can already download it.

Now the Gnome team has to review this version. Only after successful review, the version is released to the public. This usually takes some days. I think recently they have been really busy and it could even take some weeks.

If you are impatient, just install the version from upstream. (`./install.sh`)

**Comment by da-n** [comment]
Ah of course, that makes total sense thank you for explaining. I have installed from git and all working. Many thanks.
