### ISSUE TITLE
Web View's JavaScript continues to run even when closed

### ISSUE THREAD

**Issue by njam** [jaystrictor/gnome-shell-extension-syncthing#39]
When opening the _Web Interface_ in the popup window, it seems the website and its JavaScript is not removed/stopped when closing the window again.

I have confirmed this by starting syncthing with the env variable `STTRACE=http`, which makes it log all HTTP requests. After opening and closing the web interface window, I can still observe requests to `/rest/events` and many other endpoints, that result from the web interface.

This is problematic because some of these API endpoints result in increased CPU usage. So when having opened the web view once the CPU usage of Syncthing is higher :|

I haven't checked how the web view opening works. Do you think it's possible to "kill" the browser again after closing it?
Alternatively maybe just default to open in an external browser?

**Comment by jaystrictor** [comment]
> When opening the Web Interface in the popup window, it seems the website and its JavaScript is not removed/stopped when closing the window again.

That is correct. Clicking on the X symbol does not close the app, it just hides the window.
I implemented it this way, as starting the web viewer and loading the html does take some time.
By only hiding the window, the next time the web viewer is opened, it is opened instantaneously.

> I haven't checked how the web view opening works. Do you think it's possible to "kill" the browser again after closing it?

This is already possible today.
Just don't use the X symbol, but instead click on the Syncthing menu (next to "Activities") and then click on "Quit".

> Alternatively maybe just default to open in an external browser?

This is also already possible. Start `gnome-shell-extension-prefs`, open the Syncthing Icon preferences and click on "Always use external browser".

**Comment by jaystrictor** [comment]
I find it more problematic, that Syncthing produces substantial load when the GUI is open...

But anyways, for the time being it is probably better to close the window instead of hiding it.
