### ISSUE TITLE
"Configuration" versus "Launch web client"

### ISSUE THREAD

**Issue by terrycloth** [jaystrictor/gnome-shell-extension-syncthing#4]
Right now, the Syncthing Icon has a menu item labeled "Configuration," which launches the Syncthing web client. If you actually want to configure the extionsion itself, you have to launch gnome-shell-extension-prefs, or GNOME Tweak Tool, or do it on the GNOME Shell Extensions website.

Maybe, instead the "Configuration" should open the extension configuration dialog, and a separate menu item called something like "Launch web client" launches the web client.

**Comment by jaystrictor** [comment]
In the first, unpublished version that button was indeed named "Launch Web UI".

I changed it to "Configuration" in order to be able to add alternative configuration methods later, like Syncthing-GTK.
Additionally, I think every extension is configured via `gnome-shell-extension-prefs`. This is the default and we need good reasons to deviate from this "best practice".

So at the moment, I would prefer to leave it that way.

**Comment by terrycloth** [comment]
Actually, you can enable/disable and configure extensions wherever you see a list of installed extensions, so all three work: GNOME Tweak Tool, GNOME Shell Extensions Preferences, and the extensions.gnome.org website. 

There's another extension called [Freon](https://extensions.gnome.org/extension/841/freon/) that shows hardware temperatures in the Shell's top bar. If you click on the icon, at the bottom of the pop-out menu you'll see an option to configure the Sensor Settings for the extension. But what that really does is the same thing as clicking the button to configure the extension in the the GNOME Shell extension preferences. Even you click to configure the extension at extensions.gnome.org, it all opens up the same panel running on your local system. So Freon's menu item is just a shortcut, so that you don't have to open a separate gui application or navigate to a webpage to even get to the extension configuration form.

So I don't think doing the same thing for Syncthing Icon would be breaking any standards or guidelines, and it would be more convenient.

**Comment by terrycloth** [comment]
...More convenient for users who need to change the port number, that is. I don't know how complicated it would be to implement.

**Comment by jaystrictor** [comment]
Ok, so there is one extension (Freon) that has a configuration button and there are about 101 extension that don't have one. So the Freon example does not convince me at all.
I am aware that it would be easy to implement such a button as a shortcut to the configuration dialog. That's not the point.

My point is that the configuration of the Web UI URI is a one time step that the user only needs to do *once*. For this reason it should not clutter the user interface. It should stay out of sight, most of the time.

So thanks for the suggestion, but I think it's better how it is at the moment (at least as long as the configuration dialog is only used rarely. If it would be used more often, then it would be a different case...)
Closing for now.

**Comment by terrycloth** [comment]
> My point is that the configuration of the Web UI URI is a one time step that the user only needs to do *once*. For this reason it should not clutter the user interface.

That's a fair point. But what about calling it "Launch web ui" or "Launch the gui" instead? You said you changed it to Configuration so that you could add other configurations later -- but in the meanwhile, calling it Configuration seems a little inaccurate.

**Comment by jaystrictor** [comment]
I agree to call it "Launch Web UI". That seems to fit better than "Configuration".
