### ISSUE TITLE
Web interface window icon and title missing in Gnome dock

### ISSUE THREAD

**Issue by JonathanHolvey** [jaystrictor/gnome-shell-extension-syncthing#40]
I installed Syncthing Icon using Gnome's software app. Initially it worked correctly, but after changing the branch of Debian I'm using from Stable to Testing, the icon and title in the dock no longer display correctly. I've tried removing and reinstalling the extension, but without luck.

![Missing SyncThing Icon icon](https://i.imgur.com/aYw52pU.png?1)

I can see that these are set in [`webviewer.js`](https://github.com/jaystrictor/gnome-shell-extension-syncthing/blob/master/src/webviewer.js#L46-L51), however I don't know how to troubleshoot the issue. What do you suggest?

**Comment by jaystrictor** [comment]
I think this may be fixed in the latest commit.
If not and you have ideas how to fix this, please reopen.

**Comment by JonathanHolvey** [comment]
For reference, that commit ID is https://github.com/jaystrictor/gnome-shell-extension-syncthing/commit/8710428e7f81b4a624228c6bf9f75f3d965a0a6a.

**Comment by JonathanHolvey** [comment]
@jaystrictor what OS and Gnome version are you using that works with the dock icon? It doesn't appear to be a Debian issue as Fedora 30 has the same problem.

**Comment by jaystrictor** [comment]
The icon works on Arch Linux with Gnome 3.34
