### ISSUE TITLE
Grayscale icon?

### ISSUE THREAD

**Issue by SpcCw** [jaystrictor/gnome-shell-extension-syncthing#41]
Would be nice to have an option to turn the icon grayscale so it wont stand out  among others. Right now being the only colorful patch out there it catches eye as if it is alert of some sort.

There is grayscale icon in the extension folder (icons/syncthing-logo-symbolic.svg) but I am not sure how to enable it, simply replacing syncthing-logo.svg with it doesn't do the trick.

**Comment by jaystrictor** [comment]
I don't understand. For me the icon **is** grayscale. Could you post a screenshot?

**Comment by SpcCw** [comment]
Here you go.

I run Debian stable with Gnome 3.22.2 and SyncThing 0.14.54 - and I think I had it gray too in the past but now it is blue :)

To make sure I just removed the extension, checked extensions folder for any remains then restarted the system, went to https://extensions.gnome.org/extension/989/syncthing-icon/ and downloaded it for Gnome 3.22 and extension version 19 (20 doesn't work for me, fails to load - Gnome too old?). Then restarted. The folder on the screenshot is /icons folder of the installed extension.

![](https://upl.deko.cloud/image.php?di=MNKF1)

**Comment by jaystrictor** [comment]
That's weird.
If you `grep -r syncthing-logo` over the extension directory, then you can see that the colored version is only ever used in webviewer.js, which should only be started when you open the web interface.
I suppose the colored icon is shown, even before you click on "Web Interface", right?
Are you sure the icon is from this extension and not from, e.g. Syncthing-GTK or some other software?
If this is really the Syncthing Icon extension, then you could just copy `syncthing-logo-symbolic.svg` to `syncthing-logo.svg` and see if this helps?

Do you use any custom GTK icon theme (which could already contain an icon named `syncthing-logo-symbolic`)?
Check
```
find $HOME/.icons -name "syncthing-logo*"

IFS=:
for dir in $XDG_DATA_DIRS; do
    find $dir/icons -name "syncthing-logo*"
done

find /usr/share/pixmaps -name "syncthing-logo*"
```

**Comment by SpcCw** [comment]
I don't have any files called "syncthing-logo" anywhere else on the system. What is weird - even if I delete syncthing-logo.svg file from the extension/icons directory, the extension still starts (with blue icon) just web interface no longer opens. If I replace syncthing-logo.svg with syncthing-logo-symbolic.svg (so both files are grayscale) and restart then I still get blue icon in the tray and blue icon in the web interface.

I guess there is icon caching and it got stuck somehow. Deleting extension altogether and reinstalling does have same effect though. 

It seems like this is not your issue though so feel free to close unless you have some idea what needs a poke :)

Happy New Year!
```
$ cd /home/alex/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de
$ grep -r syncthing-logo

extension.js:        this._syncthingIcon = new St.Icon({ icon_name: 'syncthing-logo-symbolic',
extension.js:                                          style_class: 'system-status-icon syncthing-logo-icon' });
extension.js:            //this._syncthingIcon.icon_name = 'syncthing-logo-symbolic';
stylesheet.css:.syncthing-logo-icon {
webviewer.js:        this.set_icon_from_file('icons/syncthing-logo.svg');
```
```
$  sudo find / -name "syncthing-logo*"
/home/alex/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/icons/syncthing-logo-symbolic.svg
/home/alex/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/icons/syncthing-logo.svg
find: ‘/run/user/1000/gvfs’: Permission denied
```

**Comment by jaystrictor** [comment]
> I guess there is icon caching and it got stuck somehow.

Yes, that sounds reasonable. Have you tried deleting/regenerating the cache files?
See [official docs](https://developer.gnome.org/gtk3/stable/gtk-update-icon-cache.html) and [StackExchange](https://askubuntu.com/questions/722708/how-do-i-refresh-the-icon-cache).

Happy New Year :)

**Comment by SpcCw** [comment]
Okay, I tried to reset icon cache and create new user profile and set it to use completely untouched theme/icons before installing the extension - still blue.

However it seems like it is tied to Syncthing program itself somehow. I attached three screenshots taken one after another. On the first one the extension is freshly installed and the icon is blue. Terminal shows Syncthing is installed. On the second I just removed Syncthing and the extension icon turns gray in a few seconds (although it doesn't even know yet Syncthing isn't there so there is no "pause" indicator). On the third one I install Syncthing again and extension icon turns blue in five seconds or so. 

Step 1:
![](https://upl.deko.cloud/image.php?di=BEQIV)

Step 2:
![](https://upl.deko.cloud/image.php?di=AAW27)

Step 3:
![](https://upl.deko.cloud/image.php?di=7G6C8)

**Comment by jaystrictor** [comment]
I noticed that you use `apt.syncthing.net` and not the official debian sources.
I can reproduce the problem by switching to the `apt.syncthing.net` version of synchting. My icon is now also blue.

**Comment by SpcCw** [comment]
Interesting, I suspected it had something to do with SyncThing version since it used to be gray for me in the past and I used their repository from the start. I think it happened about two or three updates ago.

Thanks for clearing this up! If you get to fix this someday I'll appreciate mentioning this here so I can tweak it.

**Comment by jaystrictor** [comment]
This should be fixed @SpcCw
