### ISSUE TITLE
syncthing-icon issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by mdonz** [jaystrictor/gnome-shell-extension-syncthing#43]
Thank you for this excellent extension which I like and have been using since upgrade to Ubuntu 18.04. It worked fine in the beginning but has at some stage stopped to work completely but cannot remember when exactly that changed.

By "working not completely" I mean that the icon shows an exclamation mark to the right and it is greyed out to get access to the web interface. I however have access to the Syncthing web interface when manually entering the URL in my browser (localhost:8384).

I had originally reported it at syncthing itself but was pointed here:
https://forum.syncthing.net/t/web-interface-access-on-ubuntu/12840

syslog indicates issues:

Feb 13 06:03:16 twt039lt gnome-shell[3399]: Some code accessed the property 'ENABLED_EXTENSIONS_KEY' on the module 'extensionSystem'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
Feb 13 06:03:16 twt039lt gnome-shell[3399]: [syncthingicon] found syncthing config file in /home/michael/.config/syncthing
Feb 13 06:03:17 twt039lt gnome-shell[3399]: [syncthingicon] Failed to read config file /home/michael/.config/syncthing/config.xml: undefined:1:1: text data outside of root node.
Feb 13 06:03:17 twt039lt gnome-shell[3399]: [syncthingicon] Failed to connect to syncthing daemon at URI "http://localhost:8384": Forbidden
Feb 13 06:03:17 twt039lt gnome-shell[3399]: [syncthingicon] CSRF Error. Please verify your API key.

**Comment by jaystrictor** [comment]
Hey, thank you for the feedback.

This should be a duplicate of #42, which is resolved by now. I already uploaded the updated version to extensions.gnome.org, but they take some time to review extensions, so it might take a while, until the current version is published.
In the meantime you could checkout this repository and install the latest master branch by hand by just calling `./install.sh`.

**Comment by mdonz** [comment]
Thanks for the help and steps for manual installation.

I can confirm that this manual installation of the latest version fixes the issue.
