### ISSUE TITLE
Icon not visible in TopBar, but clickable

### ISSUE THREAD

**Issue by jaystrictor** [jaystrictor/gnome-shell-extension-syncthing#45]
Since an upgrade to gnome-shell 3.32, the icon is not displayed anymore in the top bar. Although the area is clickable and the menu just opens fine. I think this is a bug for how icon name lookup is handled by gnome-shell / Gio / Gtk / St.

**Version information:**
GNOME Shell 3.32.0
gjs 1.56.0

**Comment by jaystrictor** [comment]
As @coxackie pointed out in #44, there seem to be more extensions with this issue:
- neffo/bing-wallpaper-gnome-extension#48
- eonpatapon/gnome-shell-extension-caffeine#134

**Comment by coxackie** [comment]
@jaystrictor I am actually using both bing-wallpaper and caffeine, built from master, and the icons appear after the recent changes.

**Comment by jaystrictor** [comment]
@coxackie, yes I understand. I should have written that in the past tense, sorry.
I just think that this is a glib/gtk/gnome-shell issue and that all the extension authors are just doing quick and dirty hacks to get around that.

**Comment by jaystrictor** [comment]
Anyways, closing, as I am doing the same quick and dirty workaround.

**Comment by dirusulixes** [comment]
@jaystrictor not sure if it makes sense to reference such an old bug report, but I started having the same exact issue on gnome 40.4.0 and gjs 1.68.3

**Comment by jaystrictor** [comment]
@dirusulixes: You opened #61 for that. Thank you.
