### ISSUE TITLE
Request for help with an extension.

### ISSUE THREAD

**Issue by conf11s3d** [jaystrictor/gnome-shell-extension-syncthing#46]
Good evening, sorry if I write here, my name is Stefano, I ask if possible for help to an extension that the author has abandoned for about 6 years, looking at your extension too with the update to gnome shell 3.34 you had problems in viewing the icon in taskbar, the kindness I ask I was not able to clean up the errors in the file extension.js would you be kind enough to correct the file?

The extension only has 2 extension.js files - metadata.json and the icons folder

I am attaching extension.js

Thank you for your kind attention
Stephen.

[birthdays_notify@test.zip](https://github.com/jaystrictor/gnome-shell-extension-syncthing/files/3735956/birthdays_notify%40test.zip)

**Comment by jaystrictor** [comment]
I am sorry, but this is not the right place to aks for help for a different extension.
The [Extensions Mailing List](https://mail.gnome.org/mailman/listinfo/gnome-shell-extensions-list) might be the right place to aks these kinds of questions.
