### ISSUE TITLE
Syncthing icon partially broken on Gnome 3.34

### ISSUE THREAD

**Issue by deshmukhs** [jaystrictor/gnome-shell-extension-syncthing#48]
Running the latest version of Syncthing Icon on Manjaro Linux kept up-to-date. Syncthing is installed as a package from repositories - version 1.2.2-1.

In ~/.config/systemd/user, there is a file syncthing.service with the following contents:
```
[Unit]
Description=Syncthing - Open Source Continuous File Synchronization
Documentation=man:syncthing(1)

[Service]
ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0
Restart=on-failure
SuccessExitStatus=3 4
RestartForceExitStatus=3 4

[Install]
WantedBy=default.target

```
But syncthing icon does not give all the details (folders shared, their current status, etc.) as expected --- see the attached image.

Based on [https://github.com/jaystrictor/gnome-shell-extension-syncthing/issues/35]() link, I tried `systemctl --user status syncthing.service`. It produces:

```
syncthing.service - Syncthing - Open Source Continuous File Synchronization
   Loaded: loaded (/home/sandip/.config/systemd/user/syncthing.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-10-25 12:28:31 IST; 21min ago
     Docs: man:syncthing(1)
 Main PID: 934 (syncthing)
   CGroup: /user.slice/user-1000.slice/user@1000.service/syncthing.service
           └─934 /usr/bin/syncthing -no-browser -no-restart -logflags=0

```

What do I: need to do to get the extension with all its features?

![Screenshot from 2019-10-25 12-46-21](https://user-images.githubusercontent.com/4161800/67551035-8fcdf180-f725-11e9-8821-7bda2d0df51f.png)

**Comment by jaystrictor** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version information:**
 - OS: [e.g. Ubuntu 18.10]
 - `gnome-shell --version` [e.g. GNOME Shell 3.30.1]
 - `gjs --version` [e.g. gjs 1.54.3]
 - Extension version. Either via `grep '"version' ~/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/metadata.json`
   or via the git commit hash.

**Logs**
Add the output of
```
systemctl --user -n0 status syncthing.service
journalctl -b /usr/bin/gnome-shell | grep syncthingicon
```

**Comment by deshmukhs** [comment]
@jaystrictor Impatient, I am. But I am inexperienced, too. And although the instructions to manually install the extension appear straight-forward and simple, I am sure, I will mess up somewhere. So, I will rather wait till the Gnome team updates the extension.

And thanks a lot for all your help. I hope, me bringing this error to your notice has helped the project, however little. :)

Lastly, I am marking this as close and comment. Hope that is the right thing to do.

**Comment by jaystrictor** [comment]
@deshmukhs No problem being inexperienced. You did everything right. Github is a place where sometimes people are very talkative and sometimes the answers are very brief. That depends on lots of factors, also on how stressed people are. Usually it has little to do with you. Keep up the friendly tone. :)

The new version has already been approved. So you can now just update to the newest version and it should work. Please try it out and if you encounter any problems, feel free to open a new bug report.
