### ISSUE TITLE
Mirroring information on GitHub and the GNOME Extensions website

### ISSUE THREAD

**Issue by terrycloth** [jaystrictor/gnome-shell-extension-syncthing#5]
It'll probably help you avoid questions with obvious answers if you duplicate information between this repository's README and the GNOME Extensions website listing. I.e., copy the features list and the note about the systemd requirement the README to the GNOME site. And actually, I think it'd be nice to add the screenshot from the GNOME site to the README here.

**Comment by jaystrictor** [comment]
done

**Comment by terrycloth** [comment]
:+1:
