### ISSUE TITLE
Feature: Auto Pause

### ISSUE THREAD

**Issue by rvalle** [jaystrictor/gnome-shell-extension-syncthing#51]
Hi!

Would it be feasible to auto-pause on high system load? or when a Real Time application is started?

For some reason my system is often overloaded and I find myself turning on/off syncthing all the time.

Is it possible to implement this kind of functionality from a gnome extension?

some more context about the feature request: https://forum.syncthing.net/t/feature-proposal-smart-adaptative-resource-usage/14531/27

**Comment by jaystrictor** [comment]
> For some reason my system is often overloaded and I find myself turning on/off syncthing all the time.

That was exactly the reason for implementing this extension in the first place.

However, having said that, I must also state that IMHO automatically pausing is not in scope for this extension. The operating system should do a better job for these kind of aspects.
