### ISSUE TITLE
Cannot load icon theme with Gnome Shell 3.36 under Wayland

### ISSUE THREAD

**Issue by KopfKrieg** [jaystrictor/gnome-shell-extension-syncthing#53]
**Describe the bug**
The extensions is not compatible with Gnome 3.36.

**Version information:**
 - OS: Archlinux
 - GNOME Shell 3.36.0 on Wayland
 - gjs 1.64.0
 - Extension version. 26

**Logs**
```
$ systemctl --user -n0 status syncthing.service
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
     Loaded: loaded (/usr/lib/systemd/user/syncthing.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2020-03-09 23:33:51 CET; 2min 4s ago
       Docs: man:syncthing(1)
   Main PID: 2176 (syncthing)
     CGroup: /user.slice/user-1000.slice/user@1000.service/syncthing.service
             └─2176 /usr/bin/syncthing -no-browser -no-restart -logflags=0
```

```
$ journalctl -b /usr/bin/gnome-shell | grep syncthingicon
Mär 09 23:33:54 Gwynbleidd gnome-shell[2245]: JS ERROR: Extension syncthingicon@jay.strict@posteo.de: TypeError: icon_theme is null
                                               init@/home/me/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/extension.js:266:5
```
I have nearly zero experience with debugging extensions or even writing them, but if I can help you or provide any further info, let me know.

**Comment by KopfKrieg** [comment]
Argh, I'm an idiot. As the error message says, my icon theme is null. Not sure how, but changing the theme and restarting the shell fixed it. The extension is now working.

**Comment by KopfKrieg** [comment]
I'm sorry I have to reopen this. Changing the theme works, but I have to do it every time I start my PC. I'm also using the default Adwaita theme, I don't believe it's really a theme issue. The error message is still the same as in my first post.

**Comment by jaystrictor** [comment]
Works for me. I am also using Archlinux with Gnome Shell 3.36.0

Does this problem occur only in certain situations like when using the lock screen?

Could you try a pristine homedir by adding a new user temporarily and trying if it also fails for this new user?

**Comment by KopfKrieg** [comment]
Okay … so. I can uninstall and then install the extension, and then it's working. Locking the screen or using Suspend doesn't change anything. But if I log out (or restart) my laptop the extension doesn't work anymore, and I have to uninstall and then install it again.

I've also created a new user, but it behaves exactly the same.

Do you use Wayland or X11? Maybe it's a bug in Wayland?!

**Comment by KopfKrieg** [comment]
Woohoo, I fixed it

Gimme a few minutes and I'll send you a PR.
