### ISSUE TITLE
Gnome 3.36.1 shows missing icon instead of nothing when gicon is set to null

### ISSUE THREAD

**Issue by prurigro** [jaystrictor/gnome-shell-extension-syncthing#55]
**Describe the bug**

Previously setting gicon to null would hide the icon, but now you get a "missing icon" icon. This goes both for the status icon as well as the right side of each folder row.

**Screenshots**

![null-icon](https://user-images.githubusercontent.com/1149238/78172088-755e1980-7423-11ea-84a2-1f21d443aad7.png)

**Version information:**

 - OS: Arch Linux
 - GNOME Shell 3.36.1
 - gjs 1.64.1
 - Extension version: 27

**Logs**

journalctl -b /usr/bin/gnome-shell | grep syncthingicon

```
Apr 01 12:00:58 xps gnome-shell[1785]: [syncthingicon] found syncthing config file in /home/prurigro/.config/syncthing
```

**Comment by jaystrictor** [comment]
Yes, can confirm. This became a problem with the change from 3.36.0 to 3.36.1

**Comment by prurigro** [comment]
Awesome, thanks for fixing and also for the great extension!
