### ISSUE TITLE
off on button always of when syncthing is running

### ISSUE THREAD

**Issue by x0rld** [jaystrictor/gnome-shell-extension-syncthing#57]
**Describe the bug**
the button off on is always on off and when I turn it on there is a danger flag

**Screenshots**
![image](https://user-images.githubusercontent.com/45242856/81810023-84f07800-9522-11ea-9878-920391701337.png)

**Version information:**
 - OS: fedora 32
 - GNOME Shell 3.36.2
 - gjs 1.64.2
 - Extension version: c44880d14c8185f952054202f278241ce9a51c8a

**Logs**
Add the output of
```
systemctl --user -n0 status syncthing.service
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
     Loaded: loaded (/usr/lib/systemd/user/syncthing.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2020-05-13 14:03:30 CEST; 2min 33s ago
       Docs: man:syncthing(1)
    Process: 20752 ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0 (code=exited, status=1/FAILURE)
   Main PID: 20752 (code=exited, status=1/FAILURE)
        CPU: 45ms

```
journalctl -b /usr/bin/gnome-shell | grep syncthingicon
mai 13 13:54:29 ldlcpc gnome-shell[3469]: [syncthingicon] found syncthing config file in /home/x0rld/.config/syncthing
mai 13 13:59:17 ldlcpc gnome-shell[3469]: [syncthingicon] found syncthing config file in /home/x0rld/.config/syncthing
```
it's write fail but when i do this command it work
```systemctl status syncthing@x0rld
● syncthing@x0rld.service - Syncthing - Open Source Continuous File Synchronization for x0rld
     Loaded: loaded (/usr/lib/systemd/system/syncthing@.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2020-05-13 13:37:46 CEST; 30min ago
       Docs: man:syncthing(1)
   Main PID: 1220 (syncthing)
      Tasks: 22 (limit: 18791)
     Memory: 127.2M
        CPU: 11.344s
     CGroup: /system.slice/system-syncthing.slice/syncthing@x0rld.service
             ├─1220 /usr/bin/syncthing -no-browser -no-restart -logflags=0
             └─1373 /usr/bin/syncthing -no-browser -no-restart -logflags=0```

**Comment by jaystrictor** [comment]
It seems that you have accidentally switched on the systemd system service instead of the systemd user service. Try switching off the systemd system service by running
```
systemctl disable syncthing
systemctl stop syncthing
```
After that the on/off switch should work.

**Comment by x0rld** [comment]
oh yes thanks
but it will automaticly start when i start my computer ?

**Comment by jaystrictor** [comment]
If you enable linger, yes.
```
loginctl enable-linger
```

**Comment by awdav** [comment]
Thanks. I was also using Syncthing as a system service instead of a user service on Fedora 32. Using your solution solved the problem for me too.

**Comment by tmortagne** [comment]
I reproduce the same issue but the service seems to be associated with the user

```
$ systemctl --user status syncthing
● syncthing.service - Syncthing - Open Source Continuous File Synchronization
     Loaded: loaded (/usr/lib/systemd/user/syncthing.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2020-08-12 11:29:56 CEST; 1s ago
       Docs: man:syncthing(1)
    Process: 8437 ExecStart=/usr/bin/syncthing -no-browser -no-restart -logflags=0 (code=exited, status=1/FAILURE)
   Main PID: 8437 (code=exited, status=1/FAILURE)
```

```
$ systemctl status syncthing
Unit syncthing.service could not be found.
```

**Comment by tmortagne** [comment]
It just started to work for me after upgrading to Syncthing 1.8.0 (the Debian package), was failing on 1.7.1.

**Comment by jaystrictor** [comment]
@tmortagne If you are using a user service, then it should be a distinct issue and I would prefer a second GitHub issue being opened. However, I am glad it works for you now.
