### ISSUE TITLE
Indicate that syncthing has been stopped

### ISSUE THREAD

**Issue by rumpelsepp** [jaystrictor/gnome-shell-extension-syncthing#6]
It would be nice when the icon changes somehow in case syncthing is offline. Currently I have to click on the icon.

**Comment by jaystrictor** [comment]
Maybe the new "offline" icon is not the best choice. I'm no artist.
If there does exist a better design somewhere, please let me know.

**Comment by rumpelsepp** [comment]
That works for me! Thanks!
