### ISSUE TITLE
Incompatable with Gnome 41

### ISSUE THREAD

**Issue by rubberbander** [jaystrictor/gnome-shell-extension-syncthing#65]
I just upgraded to Fedora 35, and the extension is not working on Gnome 41. It cannot be enabled in the Gnome Extensions application and it is labeled as "OUTDATED" on the Gnome Extensions website. 

**Version information:**
 - OS: Fedora 35
 - GNOME Shell 41.0
 - gjs 1.70.0
 - Extension version: 29

**Comment by jaystrictor** [comment]
We are waiting for the Gnome folks to approve the latest version: https://extensions.gnome.org/review/27538

**Comment by jaystrictor** [comment]
Should be fixed now.
