### ISSUE TITLE
myLog is not defined

### ISSUE THREAD

**Issue by cdpb** [jaystrictor/gnome-shell-extension-syncthing#66]
**Describe the bug**
I receive the following error in my journal. syncthingicon behaves normal, I haven't noticed any problems, just wanted to let you know.

                                      Dez 08 01:04:06 m8 gnome-shell[1885]: [syncthingicon] Failed to connect to syncthing daemon at URI “http://localhost:8384”: Forbidden
                                      Dez 08 01:04:06 m8 gnome-shell[1885]: [syncthingicon] CSRF Error. Please verify your API key.
                                      Dez 08 01:04:06 m8 gnome-shell[1885]: [syncthingicon] Failed to connect to syncthing daemon at URI “http://localhost:8384”: Forbidden
                                      Dez 08 01:04:06 m8 gnome-shell[1885]: [syncthingicon] CSRF Error. Please verify your API key.
                                      Dez 08 01:04:06 m8 gnome-shell[1885]: [syncthingicon] Unknown syncthing folder state: 
                                      Dez 08 01:04:06 m8 gnome-shell[1885]:gnome-shell[1885]:` JS ERROR: ReferenceError: myLog is not defined

                                      _folderStateChanged@/home/m8/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/folders.js:182:17
                                      _parseFolderData@/home/m8/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:73:18
                                      `_folderReceived@/home/m8/.local/share/gnome-shell/extensions/syncthingicon@jay.strict@posteo.de/syncthing_api.js:49:14

**Version information:**
 - OS: Fedora Workstation 35
 - GNOME Shell 41.1
 - gjs 1.70.0
 - Extension version 32

Also, thanks for the work :+1:

**Comment by jaystrictor** [comment]
Thanks for the bug report. Apparently Syncthing introduced new folder states, which would not be handled by the current version of synthing icon.
