### ISSUE TITLE
Support for Ubuntu 22.04?

### ISSUE THREAD

**Issue by lupo112** [jaystrictor/gnome-shell-extension-syncthing#68]
Ubuntu 22.04 uses Gnome 42.0 which is not compatible.

Can you add support for this version?

**Comment by onefish2** [comment]
Please update this to support Gnome 42.

**Comment by cxt666** [comment]
What is needed to add Gnome 42 support?

**Comment by jaystrictor** [comment]
Just some spare time. Should be working now. Sorry for the delay.

**Comment by onefish2** [comment]
Thanks!! Its working!
