### ISSUE TITLE
Gnome 43 compatibility

### ISSUE THREAD

**Issue by Marthym** [jaystrictor/gnome-shell-extension-syncthing#71]
**Describe the bug**
Is is possible to make it compatible with Gnome 43 ?

**Version information:**
 - OS: Debian Bookworm (testing)
 - GNOME Shell 43.1
 - gjs 1.74.1
 - Extension version. 34

Thank you for this extension :pray:

**Comment by jaystrictor** [comment]
It should be compatible with Gnome 43 now. It could take some time until the Gnome team reviews the extension. In the meantime you can install it manually (see README).
