### ISSUE TITLE
LIst of folders?

### ISSUE THREAD

**Issue by a-m-s** [jaystrictor/gnome-shell-extension-syncthing#9]
The README says it lists the synced folders, but I don't have any listed. Is the documentation wrong, or did I miss a setup step?

I'm on Arch Linux with the systemd stuff all set up properly, I think. The other features work well, including starting and stopping, and opening the UI with a non-standard port.

**Comment by jaystrictor** [comment]
This was a bug. Syncthing-icon was not fetching the info from the non-standard port but tried the old standard port instead.

Can you check if it works now? To do that, check out the latest master from github, run `./install.sh` and restart gnome-shell by pressing `Alt` + `F2` and typing `r`.

**Comment by a-m-s** [comment]
The fix appears to have worked.

Thanks very much. :-)
